# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: branch
  push:
    branches:
      - "multiple-time-windows"
     

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: install packages
        run: |
         npm install
        #  sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        #  sudo wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
        #  sudo apt-get update -y
        #  sudo apt install -y libstdc++-4.9-dev
        #  sudo apt install -y clang-4.0
         